# This is a basic workflow to help you get started with Actions

name: LoadAndPack

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 */31 * *'  # 每 14 天执行一次 UTC 时间
    
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # install nodejs
      - uses: actions/setup-node@v3.9.1

      # install docker CE
      - uses: docker/setup-docker-action@v4.3.0
      
      # prepare lzc-cli and env
      - name: Prepare env etc.
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          npm install -g @lazycatcloud/lzc-cli
          sudo apt install expect curl -y
          expect -f ./int.exp "$USERNAME" "$PASSWORD"
          
          TAGS=$(docker run --rm gcr.io/go-containerregistry/crane:latest ls resilio/sync)
          LATEST_TAG=$(echo "$TAGS" | grep -v 'latest\|master\|wv' | sort -V | tail -n1)
          echo "Latest: $LATEST_TAG"
          sed -i "s/^version: .*/version: $LATEST_TAG/I" lzc-manifest.yml
      
      # replace manifest
      - name: fetch image
        run: |
          last_part=$(lzc-cli appstore copy-image resilio/sync | tail -n 1 | awk '{print $NF}')
          function escape_sed() {
            echo "$1" | sed 's/[&/\]/\\&/g'
          }
          last_part_escaped=$(escape_sed "$last_part")
          sed -i "s/##/$last_part_escaped/" lzc-manifest.yml

        
      # build
      - name: build
        run: |
          lzc-cli project build
          TAGS=$(docker run --rm gcr.io/go-containerregistry/crane:latest ls resilio/sync)
          LATEST_TAG=$(echo "$TAGS" | grep -v 'latest\|master\|wv' | sort -V | tail -n1)
          lzc-cli appstore publish ./*.lpk -c "Auto Submit: $LATEST_TAG"
      
      # upload
      - uses: actions/upload-artifact@v4.6.2
        with:
          path: ./*.lpk
